### PR TITLE
Ambiguous centuries

### PR DESCRIPTION
**Pull request by jondoveston**
Added support for ambiguous centuries (eg year 08). Defaults to current century.

### CODE REVIEW

**Comment by xaviershay** [comment]
Thanks, have added to my list of things to look at.

**Comment by jondoveston** [comment]
I've changed it a little now. The ambiguous year method will only be used for double digit years, and these will default to the last occurance of the year. I feel this is a sensible default. Consistent with the current ambiguous year logic. There is some sort of weird error in javascript dates. For me any year before 1894 is one day off and doesnt pass the tests. Not sure but could this be a rounding error in javascript? I have committed these changes, should I repeat the pull request?

**Comment by xaviershay** [comment]
No need to repeat the pull request, the new commits show up here. I will look at the new commits.

**Comment by xaviershay** [comment]
Just thinking this through ... adding support for this necessarily removes support for years 0-99, so this isn't technically backwards compatible. All the main use cases I have for Kronic are surrounding entering dates around the current times - so mostly "today", "last sunday", and support for absolute times is pretty much just for completeness. 

Adding more flexible absolute times dilutes the main purpose of the library. For a related example, it doesn't support "4/5/2010" format because it is ambiguous depending on which locale you are in. Ambiguous centuries probably fall into the same class of feature.

Further, even though 12 resolving to 1912 is technically correct given the rest of the code is backwards looking, this doesn't seem useful.

Adding this feature adds extra complexity and makes me nervous. What is your use case for this? Do you have users that are entering ambiguous centuries?

**Comment by iHiD** [comment]
I feel that 12 is obviously 2012 and 98 is obviously 1998. However, determining why that's obvious to me is difficult. Initially I thought that the nearest occurrence of that year makes the most sense (so 1961 to 2061) but having thought about it more, I'm not sure. 

My conclusion is that the use of this will be specific to the application. For an app with birthdays, you want it to default to the past. For something for financial forecasting, you'd want it to default forward.

Because it's SO application specific, I'm not sure it should be a core function. 

So the question is do we want to start bringing in configuration options? This treads on the same territory as the 04/05/2011 questions with locales. I'm happy to go with config settings (and for this, that would be :nearest_year, :past, :future or something), but that's your decision, Xavier. Thoughts?

**Comment by xaviershay** [comment]
Based on that, I think perhaps the best way forward is to provide solid extension points in the library and leave it up to the app to customize? Currently I think is difficult because everything is a class method, but still possible. Though you could do:

```
Kronic.parse(date) || my_custom_parse(date)
```

to catch other formats and maybe that is sufficient? That would fix the 3/4/2011 problems and ambiguos centuries problem. Doesn't address not being able to assume dates in the future though. Perhaps would be nice if you could subclass Kronic, though we then need a JS solution, and is probably getting into fork territory now.

**Comment by jondoveston** [comment]
My initial attempt to parse the ambiguous century dates using kronic was to look for a not_before or a within_range configuration option. My case where I've been asked to parse a set of differently formatted dates (not datetimes), but dates that I know are all quite recent, kronic seemed a good solution. The most general case I see is when you parse a date string you get back an array of possible dates, depending on any ambiguity in any of the string. Then you put this through a within_range filter and hopefully get a single date. Perhaps kronic could implement this but only return the first in the array by default (maintaining backwards compatibility) and application extensions could get back the array.

**Comment by iHiD** [comment]
"A dirt simple library for parsing and formatting human readable dates..."

I feel like we might be moving away from this remit. That's not necessarily a bad thing, but it's a big decision to make.

**Comment by xaviershay** [comment]
I tend to agree. I'm not opposed to "Dirt simple that you can extend" though. Going to close this pull request and have more of a think about allowing that. Thanks for both your input!

**Comment by jogaco** [comment]
I think this would be useful. You could add a default century param to the parse method.

**Comment by xaviershay** [comment]
@jogaco what would you use it for?

**Comment by jogaco** [comment]
I need to parse free text event dates. Some do not contain a year because it is the current year. Some might contain a year in the near future and some other might contain a year in the past. I need to discard the ones in the future.

**Pull request closed without merging**
